### ISSUE TITLE
Using docker args to simplify work

### ISSUE THREAD

**Issue by Hartorn** [BurnySc2/python-sc2-docker#3]
Hello,

Came across this repo, while looking around python-sc2
I see you are using several branches to handle several python version and SCII

I think we may simplify this using docker ARG, to have only one make file.
If it's not possible (different maps by version, ...), we may still automate dockerfile update.

Also, using build-stage step in dockerfile may allow to have an image a bit lighter.

Tell me if you are interested in trying this out, I can help you out or give it a try

**Comment by Hartorn** [comment]
@BurnySc2 Not sure if you are seeing this or not, so trying to bump

**Comment by BurnySc2** [comment]
Wops, I have read this only now, sorry!

Hmm I'm honestly unsure what you are saying since I don't know much about linux and docker.
I just wanted this to work, so I could use it for travis CI on https://github.com/Dentosal/python-sc2 to be able to automatically test if the library is working, if game can be run at all or if there are runtime problems.

**Comment by Hartorn** [comment]
@BurnySc2 No problem ;)

Basically, what I was saying was : instead of having N git branches for every python version, you could have one, and in the Dockerfile, use an argument.

I could make a merge request on that, so you would be able to test it if you want. 
We could also setup continuous integration, so every time a change is made onto the image, it's built and sent to Dockerhub

**Comment by BurnySc2** [comment]
Short update:
I think I made it work now using github actions and docker hub (since it seems like docker hub no longer allows you to automatically build images on their servers).

Now ideally I want to not overwrite images, but I guess I'll have to add that another time.
Closing this issue for now.
